version: '3.8'

services:
  llm-firewall:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LLM_FIREWALL_PORT=3000
      - LLM_FIREWALL_LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s